### ISSUE TITLE
BWT Forward+Inverse difference for a particular size.

### ISSUE THREAD

**Issue by pzo** [flanglet/kanzi-go#1] opened 2019-08-22 12:31 UTC
With a source starting at length 6291456 BWT Forward+Inverse does not result in original contents. See example enclosed.

[demo.zip](https://github.com/flanglet/kanzi-go/files/3530119/demo.zip)

**Comment by flanglet** [comment] 2019-08-22 19:27
Thank you for reporting the problem .
The issue is a regression in the rewrite of the BWT inverse in release 1.6. The code is not working properly with several chunks in some cases. I will take a deeper look over the week-end. In the meantime a workaround is to always return 1 in "GetBWTChunks(size int) int".

**Comment by flanglet** [comment] 2019-08-23 03:12
I found the issue and it is not a regression. In fact the code works correctly when called appropriately.
In past releases, I added code to divide big blocks into chunks (up to 8) that can be processed in parallel. Small blocks have 1 chunk always. It means that up to 8 primary indexes must be kept in the transformed data. My test code is far from perfect and I use only small blocks (only 1 primary index). But for bigger block all primary indexes must be set prior to calling the inverse. In your case, you need to set primary indexes 0 and 1 (2 chunks for block size 6291456) like this:
	idx1 = bwtTransform.PrimaryIndex(0)
	idx2 := bwtTransform.PrimaryIndex(1)
	fmt.Printf("primary: %v %v\n", idx1, idx2)

	if bwtTransform, err = kanzi.NewBWT(); err != nil {
		log.Fatal("NewBWT", err)
	}
	bwtTransform.SetPrimaryIndex(0, idx1)
	bwtTransform.SetPrimaryIndex(1, idx2)

A more correct version (that I am going to add to my test code shortly) is to call getBWTChunks(size) to get the number of primary indexes and set them all in a loop before calling inverse.

**Comment by flanglet** [comment] 2019-08-23 16:44
Improved test code with commit 6335f63. Closing

**Closed by flanglet** 2019-08-23 16:44 UTC
